name: fast-bert-ner
channels:
  - conda-forge
dependencies:
  - python=3.7.8
  - numpy>=1.17.0
  - pandas>=1.0.0
  - scikit-learn=0.19.1
  - pip:
    - mlflow
    - azureml-mlflow
    - transformers
    - torch
    - fast-bert